apiVersion: v1
kind: Secret
metadata:
  name: cosign-public-key
  namespace: gerbangkube-system
type: Opaque
stringData:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv7w1m7KKbmtrziLv7JbV6Sub5mbl
    QbKH/nIGvprBV1oEj5NppzsKQdd/oIcSDN+O4LpSAVXzGU61lLy38tjN+g==
    -----END PUBLIC KEY-----
