apiVersion: v1
kind: Secret
metadata:
  name: cosign-public-key
  namespace: gerbangkube-system
type: Opaque
stringData:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_COSIGN_PUBLIC_KEY
    -----END PUBLIC KEY-----
